"""empty message

Revision ID: 3bdf0fdc4028
Revises: 5436fd4dfc35
Create Date: 2018-03-14 08:57:28.647409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdf0fdc4028'
down_revision = '5436fd4dfc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column(
        'sct_code', sa.String(), nullable=False))
    op.create_index('only_one_active_medication', 'medication', [
                    'name'], unique=True, postgresql_where=sa.text('deleted IS NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('only_one_active_medication', table_name='medication')
    op.drop_column('medication', 'sct_code')
    # ### end Alembic commands ###
