"""empty message

Revision ID: 955292e25fbc
Revises: 36118e617124
Create Date: 2018-01-11 14:53:36.407394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955292e25fbc'
down_revision = '36118e617124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column(
        'deleted', sa.DateTime(), nullable=True))
    op.drop_constraint('medication_name_key', 'medication', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('medication_name_key', 'medication', ['name'])
    op.drop_column('medication', 'deleted')
    # ### end Alembic commands ###
