"""drop tags

Revision ID: ef563dfdc6bc
Revises: 0a3d8bf8e503
Create Date: 2020-10-27 12:23:44.337267

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ef563dfdc6bc"
down_revision = "0a3d8bf8e503"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TABLE relationship_table CASCADE")
    op.execute("DROP TABLE tag CASCADE")
    op.add_column("medication", sa.Column("tags", sa.JSON(), nullable=True))
    op.execute("UPDATE medication SET tags = '[]'")
    op.alter_column("medication", "tags", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medication", "tags")
    op.create_table(
        "tag",
        sa.Column("uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "modified", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("tag", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_by_",
            sa.VARCHAR(),
            server_default=sa.text("'sys'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_by_",
            sa.VARCHAR(),
            server_default=sa.text("'sys'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name="tag_pkey"),
        sa.UniqueConstraint("tag", name="tag_tag_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "relationship_table",
        sa.Column("medication_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medication.uuid"],
            name="relationship_table_medication_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tag.uuid"], name="relationship_table_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "medication_id", "tag_id", name="relationship_table_pkey"
        ),
    )
    # ### end Alembic commands ###
